name: Sync to Gitee

on:
  push:
    branches:
      - main  # 或者你想要同步的分支

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to Gitee
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
        run: |
          git config --global user.name "zhongba"
          git config --global user.email "zhong.ba@foxmail.com"
          git remote add gitee git@gitee.com:zhongba/ai-demo.git
          git push gitee main --force  # 替换为你想要同步的分支
